### ISSUE TITLE
Connection issue when using ec2-user

### ISSUE THREAD

**Issue by strongishllama** [BrianFarnhill/AWSDeveloperEnvironment#2]
I wasn't able to get this working until I changed **ec2-user** to **ubuntu**. I'm happy to update the README with a PR if this is expected behaviour.

**Comment by BrianFarnhill** [comment]
@strongishllama What OS are you using as the base image? ec2-user is what comes out if you are using Amazon Linux 1/2, Ubuntu is what happens with the Ubuntu OS. Did you change the OS image from what I had defined in there?

**Comment by strongishllama** [comment]
@BrianFarnhill Ah of course! My bad, I inherited the project with it looks like some modifications and didn't realise originally it was using Amazon Linux. Closing off now.
